// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ORMcoreApp.DataAcces;

namespace ORMcoreApp.Migrations
{
    [DbContext(typeof(PoliceManContent))]
    [Migration("20210311204236_GunHasChanges")]
    partial class GunHasChanges
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ORMcoreApp.Models.Automobilis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CarMake")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CarModel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Passengers")
                        .HasColumnType("int");

                    b.Property<string>("VinId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("automobiliai");
                });

            modelBuilder.Entity("ORMcoreApp.Models.DienosAutomobilis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("automobilisId")
                        .HasColumnType("int");

                    b.Property<DateTime>("day")
                        .HasColumnType("datetime2");

                    b.Property<int?>("pareigunasId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("automobilisId");

                    b.HasIndex("pareigunasId");

                    b.ToTable("skirtinguDienuAutomobiliai");
                });

            modelBuilder.Entity("ORMcoreApp.Models.Ginklas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GunID")
                        .HasColumnType("int");

                    b.Property<string>("GunModel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GunName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("ginklai");
                });

            modelBuilder.Entity("ORMcoreApp.Models.Pareigunas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LastName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Name")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Role")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.Property<int>("ginklasId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ginklasId")
                        .IsUnique();

                    b.ToTable("pareigunai");
                });

            modelBuilder.Entity("ORMcoreApp.Models.UzduociuListas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<DateTime>("day")
                        .HasColumnType("datetime2");

                    b.Property<int>("pareigunasId")
                        .HasColumnType("int");

                    b.Property<int?>("uzduotisId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("pareigunasId")
                        .IsUnique();

                    b.HasIndex("uzduotisId");

                    b.ToTable("uzduociuListai");
                });

            modelBuilder.Entity("ORMcoreApp.Models.Uzduotis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Uzduotys");
                });

            modelBuilder.Entity("ORMcoreApp.Models.DienosAutomobilis", b =>
                {
                    b.HasOne("ORMcoreApp.Models.Automobilis", "automobilis")
                        .WithMany("SkirtinguDienuAutomobilis")
                        .HasForeignKey("automobilisId");

                    b.HasOne("ORMcoreApp.Models.Pareigunas", "pareigunas")
                        .WithMany("SkirtinguDienuAutomobilis")
                        .HasForeignKey("pareigunasId");

                    b.Navigation("automobilis");

                    b.Navigation("pareigunas");
                });

            modelBuilder.Entity("ORMcoreApp.Models.Pareigunas", b =>
                {
                    b.HasOne("ORMcoreApp.Models.Ginklas", "ginklas")
                        .WithOne("pareigunas")
                        .HasForeignKey("ORMcoreApp.Models.Pareigunas", "ginklasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ginklas");
                });

            modelBuilder.Entity("ORMcoreApp.Models.UzduociuListas", b =>
                {
                    b.HasOne("ORMcoreApp.Models.Pareigunas", "pareigunas")
                        .WithOne("uzduociuListas")
                        .HasForeignKey("ORMcoreApp.Models.UzduociuListas", "pareigunasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ORMcoreApp.Models.Uzduotis", "uzduotis")
                        .WithMany("Uzduotys")
                        .HasForeignKey("uzduotisId");

                    b.Navigation("pareigunas");

                    b.Navigation("uzduotis");
                });

            modelBuilder.Entity("ORMcoreApp.Models.Automobilis", b =>
                {
                    b.Navigation("SkirtinguDienuAutomobilis");
                });

            modelBuilder.Entity("ORMcoreApp.Models.Ginklas", b =>
                {
                    b.Navigation("pareigunas");
                });

            modelBuilder.Entity("ORMcoreApp.Models.Pareigunas", b =>
                {
                    b.Navigation("SkirtinguDienuAutomobilis");

                    b.Navigation("uzduociuListas");
                });

            modelBuilder.Entity("ORMcoreApp.Models.Uzduotis", b =>
                {
                    b.Navigation("Uzduotys");
                });
#pragma warning restore 612, 618
        }
    }
}
